### ISSUE TITLE
[Tracking] Todo (general):

### ISSUE THREAD

**Issue by VytorCalixto** [PETComputacaoUFPR/Hyde#1]
- [ ] Upload of assets (images, videos, etc)
- [ ] Download of assets
- [ ] Post to Facebook
- [ ] Full control of posts (drafts, creation, editing)
